// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.Eight/Compiling/index.js

(module.exports = require('./namespace'))

.addModules({
  CustomNodes:            require('./CustomNodes'),
  NodeBaseClass:          require('./NodeBaseClass'),
  Nodes:                  require('./Nodes'),
  RuleGroupNodeBaseClass: require('./RuleGroupNodeBaseClass')
});