# generated by Neptune Namespaces v3.x.x
# file: tests/Caffeine.Eight/Compiling/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CustomNodes:            require './CustomNodes'           
  NodeBaseClass:          require './NodeBaseClass'         
  Nodes:                  require './Nodes'                 
  RuleGroupNodeBaseClass: require './RuleGroupNodeBaseClass'