// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.Eight/Compiling/namespace.js

module.exports = require('../namespace').addNamespace(
  'Compiling',
  class Compiling extends Neptune.PackageNamespace {}
);
