// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.Eight/Parsing/index.js

(module.exports = require('./namespace'))

.addModules({
  Labels:                        require('./Labels'),
  LeftRecursive:                 require('./LeftRecursive'),
  Parser:                        require('./Parser'),
  ParserExtensionViaInheritance: require('./ParserExtensionViaInheritance')
});