# generated by Neptune Namespaces v3.x.x
# file: tests/Caffeine.Eight/Parsing/namespace.coffee

module.exports = (require '../namespace').addNamespace('Parsing', class Parsing extends Neptune.PackageNamespace)
