# generated by Neptune Namespaces v1.x.x
# file: tests/BabelBridge/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.BabelBridge ||
Tests.addNamespace 'BabelBridge', class BabelBridge extends Neptune.Base
  ;