# generated by Neptune Namespaces v3.x.x
# file: tests/BabelBridge/namespace.coffee

module.exports = (require '../namespace').addNamespace 'BabelBridge', class BabelBridge extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './Compiling/namespace';
require './Extensions/namespace';
require './FailingParseInfo/namespace';
require './Parsing/namespace'