# generated by Neptune Namespaces v2.x.x
# file: tests/BabelBridge/namespace.coffee

module.exports = (require '../namespace').addNamespace('BabelBridge', class BabelBridge extends Neptune.Base)
require './Compiling/namespace';
require './Extensions/namespace';
require './FailingParseInfo/namespace';
require './Parsing/namespace'