# generated by Neptune Namespaces v3.x.x
# file: Caffeine.Eight/Extensions/namespace.coffee

module.exports = (require '../namespace').addNamespace('Extensions', class Extensions extends Neptune.PackageNamespace)
