// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.Eight/Extensions/index.js

(module.exports = require('./namespace'))

.addModules({
  IndentBlocksParsing: require('./IndentBlocksParsing')
});