# generated by Neptune Namespaces v1.x.x
# file: tests/babel_bridge/index.coffee

module.exports = require './namespace'
.addModules
  CustomNodes:                   require './custom_nodes'                    
  IndentBlocksParsing:           require './indent_blocks_parsing'           
  Labels:                        require './labels'                          
  ParserExtensionViaInheritance: require './parser_extension_via_inheritance'
  Parser:                        require './parser'                          