# generated by Neptune Namespaces v0.5
# file: tests/babel_bridge/index.coffee

module.exports = require './namespace'
.addModules
  CustomNodes:   require './custom_nodes'  
  IndentBlocks:  require './indent_blocks' 
  IndentBlocks2: require './indent_blocks2'
  Labels:        require './labels'        
  Parser:        require './parser'        