# generated by Neptune Namespaces v0.5
# file: tests/babel_bridge/index.coffee

module.exports = require './namespace'
.addModules
  CustomNodes:         require './custom_nodes'         
  IndentBlocksParsing: require './indent_blocks_parsing'
  Labels:              require './labels'               
  Parser:              require './parser'               