# generated by Neptune Namespaces
# file: tests/babel_bridge/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.BabelBridge ||
Tests.addNamespace class BabelBridge extends Neptune.Base
  ;