# generated by Neptune Namespaces v0.3.0
# file: tests/babel_bridge/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.BabelBridge ||
Tests.addNamespace 'BabelBridge', class BabelBridge extends Neptune.Base
  ;