# generated by Neptune Namespaces v0.6
# file: babel_bridge/Extensions/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Extensions ||
BabelBridge.addNamespace 'Extensions', class Extensions extends Neptune.Base
  ;