// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.Eight/FailingParseInfo/index.js

(module.exports = require('./namespace'))

.addModules({
  CouldHaveContinued: require('./CouldHaveContinued')
});