# generated by Neptune Namespaces v3.x.x
# file: tests/Caffeine.Eight/FailingParseInfo/namespace.coffee

module.exports = (require '../namespace').addNamespace('FailingParseInfo', class FailingParseInfo extends Neptune.PackageNamespace)
