// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.Eight/FailingParseInfo/namespace.js

module.exports = require('../namespace').addNamespace(
  'FailingParseInfo',
  class FailingParseInfo extends Neptune.PackageNamespace {}
);
