# generated by Neptune Namespaces v1.x.x
# file: tests/BabelBridge/Compiling/index.coffee

module.exports = require './namespace'
.addModules
  CustomNodes:            require './CustomNodes'           
  NodeBaseClass:          require './NodeBaseClass'         
  RuleGroupNodeBaseClass: require './RuleGroupNodeBaseClass'