# generated by Neptune Namespaces v1.x.x
# file: tests/BabelBridge/Compiling/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Compiling ||
BabelBridge.addNamespace 'Compiling', class Compiling extends Neptune.Base
  ;