# generated by Neptune Namespaces v3.x.x
# file: tests/BabelBridge/Compiling/namespace.coffee

module.exports = (require '../namespace').addNamespace('Compiling', class Compiling extends Neptune.PackageNamespace)
