// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Eight/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Eight'))
.addModules({
  CaffeineEightCompileError: require('./CaffeineEightCompileError'),
  Lib:                       require('./Lib'),
  NonMatch:                  require('./NonMatch'),
  Parser:                    require('./Parser'),
  PatternElement:            require('./PatternElement'),
  Repl:                      require('./Repl'),
  Rule:                      require('./Rule'),
  RuleVariant:               require('./RuleVariant'),
  SourceLineColumnMap:       require('./SourceLineColumnMap'),
  Stats:                     require('./Stats')
});
require('./Extensions');
require('./Nodes');