# generated by Neptune Namespaces v3.x.x
# file: Caffeine.Eight/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Eight'
.addModules
  CaffeineEightCompileError: require './CaffeineEightCompileError'
  Lib:                       require './Lib'                      
  NonMatch:                  require './NonMatch'                 
  Parser:                    require './Parser'                   
  PatternElement:            require './PatternElement'           
  Repl:                      require './Repl'                     
  Rule:                      require './Rule'                     
  RuleVariant:               require './RuleVariant'              
  SourceLineColumnMap:       require './SourceLineColumnMap'      
  Stats:                     require './Stats'                    
require './Extensions'
require './Nodes'