// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Eight/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Caffeine.Eight',
  (class Eight extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Extensions/namespace');
require('./Nodes/namespace');