# generated by Neptune Namespaces v3.x.x
# file: Caffeine.Eight/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Caffeine.Eight', class Eight extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Extensions/namespace';
require './Nodes/namespace'