# generated by Neptune Namespaces v3.x.x
# file: tests/Caffeine.Eight/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Lib:                 require './Lib'                
  SourceLineColumnMap: require './SourceLineColumnMap'
require './Compiling'
require './Extensions'
require './FailingParseInfo'
require './Parsing'