# generated by Neptune Namespaces v3.x.x
# file: tests/Caffeine.Eight/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Caffeine.Eight', class Eight extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './Compiling/namespace';
require './Extensions/namespace';
require './FailingParseInfo/namespace';
require './Parsing/namespace'