// generated by Neptune Namespaces v4.x.x
// file: tests/Caffeine.Eight/namespace.js

module.exports = require('../namespace').addNamespace(
  'Caffeine.Eight',
  (class Eight extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./Compiling/namespace');
require('./Extensions/namespace');
require('./FailingParseInfo/namespace');
require('./Parsing/namespace');