# generated by Neptune Namespaces v1.x.x
# file: babel_bridge/nodes/index.coffee

module.exports = require './namespace'
.addModules
  EmptyNode:         require './empty_node'         
  EmptyOptionalNode: require './empty_optional_node'
  Node:              require './node'               