# generated by Neptune Namespaces v0.1.0
# file: babel_bridge/nodes/index.coffee

(module.exports = require './namespace')
.addModules
  EmptyNode:    require './empty_node'
  Node:         require './node'
  RootNode:     require './root_node'
  RuleNode:     require './rule_node'
  TerminalNode: require './terminal_node'