# generated by Neptune Namespaces v1.x.x
# file: babel_bridge/nodes/index.coffee

module.exports = require './namespace'
.addModules
  EmptyNode:         require './EmptyNode'        
  EmptyOptionalNode: require './EmptyOptionalNode'
  Node:              require './node'             