# generated by Neptune Namespaces v0.1.0
# file: babel_bridge/nodes/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Nodes ||
BabelBridge.addNamespace class Nodes extends Neptune.Base
  ;