# generated by Neptune Namespaces v0.3.0
# file: babel_bridge/nodes/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Nodes ||
BabelBridge.addNamespace 'Nodes', class Nodes extends Neptune.Base
  ;