# generated by Neptune Namespaces v1.x.x
# file: BabelBridge/index.coffee

module.exports = require './namespace'
.addModules
  BabelBridgeCompileError: require './BabelBridgeCompileError'
  NonMatch:                require './NonMatch'               
  Parser:                  require './Parser'                 
  PatternElement:          require './PatternElement'         
  Rule:                    require './Rule'                   
  RuleVariant:             require './RuleVariant'            
  Stats:                   require './Stats'                  
  Tools:                   require './Tools'                  
require './Extensions'
require './Nodes'