# generated by Neptune Namespaces v3.x.x
# file: BabelBridge/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'BabelBridge', class BabelBridge extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Extensions/namespace';
require './Nodes/namespace'