# generated by Neptune Namespaces v2.x.x
# file: BabelBridge/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace('BabelBridge', class BabelBridge extends Neptune.Base)
require './Extensions/namespace';
require './Nodes/namespace'