# generated by Neptune Namespaces v2.x.x
# file: BabelBridge/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.BabelBridge ||
Neptune.addNamespace 'BabelBridge', class BabelBridge extends Neptune.Base
  ;
require './Extensions/namespace';
require './Nodes/namespace'