# generated by Neptune Namespaces v1.x.x
# file: BabelBridge/Extensions/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Extensions ||
BabelBridge.addNamespace 'Extensions', class Extensions extends Neptune.Base
  ;