# generated by Neptune Namespaces v3.x.x
# file: tests/BabelBridge/Extensions/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  IndentBlocksParsing: require './IndentBlocksParsing'