# generated by Neptune Namespaces v2.x.x
# file: tests/BabelBridge/Extensions/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Extensions ||
BabelBridge.addNamespace 'Extensions', class Extensions extends Neptune.Base
  ;
