# generated by Neptune Namespaces v2.x.x
# file: tests/BabelBridge/Extensions/namespace.coffee

module.exports = (require '../namespace').addNamespace('Extensions', class Extensions extends Neptune.Base)
