# generated by Neptune Namespaces v2.x.x
# file: tests/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace('Tests', class Tests extends Neptune.Base)
require './BabelBridge/namespace'