# generated by Neptune Namespaces v3.x.x
# file: tests/BabelBridge/FailingParseInfo/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CouldHaveContinued: require './CouldHaveContinued'