# generated by Neptune Namespaces v2.x.x
# file: tests/BabelBridge/FailingParseInfo/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.FailingParseInfo ||
BabelBridge.addNamespace 'FailingParseInfo', class FailingParseInfo extends Neptune.Base
  ;
