# generated by Neptune Namespaces v2.x.x
# file: tests/BabelBridge/FailingParseInfo/namespace.coffee

module.exports = (require '../namespace').addNamespace('FailingParseInfo', class FailingParseInfo extends Neptune.Base)
