# generated by Neptune Namespaces v2.x.x
# file: BabelBridge/Nodes/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  EmptyNode:         require './EmptyNode'        
  EmptyOptionalNode: require './EmptyOptionalNode'
  Node:              require './Node'             
  ScratchNode:       require './ScratchNode'      