# generated by Neptune Namespaces v1.x.x
# file: BabelBridge/Nodes/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Nodes ||
BabelBridge.addNamespace 'Nodes', class Nodes extends Neptune.Base
  ;