# generated by Neptune Namespaces v0.1.0
# file: babel_bridge/index.coffee

(module.exports = require './namespace')
.addModules
  Parser:         require './parser'
  PatternElement: require './pattern_element'
  Rule:           require './rule'
  RuleVariant:    require './rule_variant'
require './nodes'