# generated by Neptune Namespaces v0.5
# file: babel_bridge/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.BabelBridge ||
Neptune.addNamespace 'BabelBridge', class BabelBridge extends Neptune.Base
  ;