# generated by Neptune Namespaces v0.1.0
# file: babel_bridge/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.BabelBridge ||
Neptune.addNamespace class BabelBridge extends Neptune.Base
  ;