# generated by Neptune Namespaces v3.x.x
# file: tests/BabelBridge/Parsing/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Labels:                        require './Labels'                       
  LeftRecursive:                 require './LeftRecursive'                
  Parser:                        require './Parser'                       
  ParserExtensionViaInheritance: require './ParserExtensionViaInheritance'