# generated by Neptune Namespaces v1.x.x
# file: tests/BabelBridge/Parsing/index.coffee

module.exports = require './namespace'
.addModules
  Labels:                        require './Labels'                       
  Parser:                        require './Parser'                       
  ParserExtensionViaInheritance: require './ParserExtensionViaInheritance'