# generated by Neptune Namespaces v1.x.x
# file: tests/BabelBridge/Parsing/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.Parsing ||
BabelBridge.addNamespace 'Parsing', class Parsing extends Neptune.Base
  ;