# generated by Neptune Namespaces v1.x.x
# file: tests/babel_bridge/FailingParseInfo/index.coffee

module.exports = require './namespace'
.addModules
  CouldHaveContinued: require './CouldHaveContinued'