# generated by Neptune Namespaces v1.x.x
# file: tests/babel_bridge/FailingParseInfo/namespace.coffee

BabelBridge = require '../namespace'
module.exports = BabelBridge.FailingParseInfo ||
BabelBridge.addNamespace 'FailingParseInfo', class FailingParseInfo extends Neptune.Base
  ;