// generated by Neptune Namespaces v4.x.x
// file: Caffeine.Eight/Nodes/namespace.js

module.exports = require('../namespace').addNamespace(
  'Nodes',
  class Nodes extends Neptune.PackageNamespace {}
);
