# generated by Neptune Namespaces v1.x.x
# file: BabelBridge/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.BabelBridge ||
Neptune.addNamespace 'BabelBridge', class BabelBridge extends Neptune.Base
  ;